name: '${name}'
version: '${version}'
main: '${main}'

authors:
  - Drak

folia-supported: true

depend:
  - BukkitOfUtils

commands:
  progression:
    description: Manage player progression
    aliases:
      - prog